trigger:
- main

pr:
- main

pool:
  name: aws-self-hosted-agent

steps:
- script: echo Test => Hello, world!
  displayName: 'Test script'


- task: AWSShellScript@1
  inputs:
    awsCredentials: 'azure_user_SC'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'ls '


