trigger:
  branches:
    include:
    - main

pr:
- main

pool:
  name: aws-self-hosted-agent

steps:
- script: |
    echo Test => Hello, world!
    cd TerraformCode
    ls
  displayName: 'Test script'

