---
- name: Update yum cache
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install Java
  yum:
    name: java-11-openjdk-devel
    state: present

- name: Create ec2-user Slave Folder
  file:
    path: "jenkins_slave"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Install Docker
  yum:
    name: docker
    state: present
    update_cache: yes

- name: Add ec2-user user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
